version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iga
      MYSQL_USER: root
      MYSQL_PASSWORD: iga_pass
    ports:
      - "3305:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql

volumes:
  mysql_data_volume:
    external: true
    name: 646c7369f3293e2e86b7bce13f298493b7f63e9866c80ef1bf049f16b4b48a95
