version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iga-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iga
      MYSQL_USER: iga_user
      MYSQL_PASSWORD: iga_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
